---
- hosts: server
  tasks:
  - name: "Run the birdwatcherclient container"
    docker_container:
      name: myangular
      image: birdwatcherclient
      ports:
      - 80:80
  - name: Check if container is running
    shell: docker ps